# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ce80cc3ab6ec171f2482df1145255d68104c8a647de8c2b31307dafc4be82f1b713800bcda859a61523b881d027c0e9fe9fb36b0ea449d758bd09b0e310e4af

test:
  secret_key_base: 26cac5a17b2e418f1e67ee7731c7da19ad50e1344d7e45ef60abcb3eea59992d1a3d68cc663a607fc398e73bfadbd59beb07e19d7c0406c2fb8056be30c6ebeb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
